---
- name: Install and configure MariaDb
  hosts: db
  become: true

  roles:
    - role: db_maria

- name: Install and configure PostgreSQL
  hosts: db-test
  become: true

  roles:
    - role: db_maria    

#- import_playbook: server.yml
- name: Install and configure Apache
  hosts: server
  become: true

  roles:
    - role: server      
