- name: Start message
  ansible.builtin.debug:
    msg: 'Create task to install and preparing DB server'

- name: "Install packages"
  apt: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-contrib

- name: "Install Python packages"
  pip: "name={{ item }}  state=present"
  with_items:
    - psycopg2-binary