- name: Start message
  ansible.builtin.debug:
    msg: 'Create task to install and preparing DB server'

- name: "Install packages"
  apt: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-contrib

- name: "Install Python packages"
  pip: "name={{ item }}  state=present"
  with_items:
    - psycopg2-binary

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data    

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql
  notify: restart postgresql