- name: Start message
  ansible.builtin.debug:
    msg: 'Create task to install and preparing DB server'

- name: "Install packages"
  apt: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-contrib
