- name: Start message
  ansible.builtin.debug:
    msg: 'Create task to install and preparing DB server'

- name: Generate for database
  ansible.builtin.set_fact:
    login_user: root
    login_pass: lookup('community.general.random_string')
    root_pass: lookup('community.general.random_string')
  when: lookup('ansible.builtin.env', 'CI') == 'true'

- name: "Install packages"
  apt: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-client

- name: "Install Python packages"
  pip: "name={{ item }}  state=present"
  with_items:
    - psycopg2-binary

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data    

#- name: "Initialize PostgreSQL"
#  shell: /usr/pgsql-14/bin/postgresql-setup initdb
#  when: not postgres_data.stat.exists

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql
  notify: restart postgresql

- name: Create the database specified in vars
  become: true
  become_user: postgres
  postgresql_db: name={{ db_name }}
      template='template0'
      state=present
- name: Ensure user has access to the new database
  become: true
  become_user: postgres
  postgresql_user: db={{ db_name }}
      name={{ db_user }}
      password={{ db_pass }}
      priv=ALL
      state=present
- name: Ensure user does not have unnecessary permissions
  become: true
  become_user: postgres
  postgresql_user: name={{ db_user }}
      role_attr_flags=NOSUPERUSER,NOCREATEDB
      state=present