
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install PostgreSQL and psycopg2 (Python library for PostgreSQL)
  apt:
    name: "{{ item }}"
  loop:
    - postgresql
    - postgresql-contrib
    - python3-psycopg2 # Install psycopg2 for Python 3
    
- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
  - postgresql

- name: Create a PostgreSQL database
  postgresql_db:
    name: "{{ db_name }}"  # Replace with your desired database name
    state: present

- name: Configure PostgreSQL authentication
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
  notify: restart postgresql   

- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres    
    #priv: "{{ db_name }}.*:ALL"

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
  become: true
  become_user: postgres
    
 