galaxy_info:
  author: Oleksandr Tarakanov
  description: Laravel app instalation and configuration role
  company: ansible-roles-team-mp3
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: '2.1'
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
  galaxy_tags: []    
dependencies: []
  